alter table users enable row level security;
alter table groups enable row level security;
alter table group_members enable row level security;
alter table invite_tokens enable row level security;
alter table group_participant_bindings enable row level security;
alter table expenses enable row level security;
alter table expense_splits enable row level security;
alter table settlements enable row level security;
alter table group_view_events enable row level security;
